### ISSUE TITLE
reproduction results on the validation set

### ISSUE THREAD

**Issue by tfzhou** [idilesenzulfikar/UNOVOST#1]
Hi, @idilesenzulfikar 

Thanks for the great project. I have successfully made premvos and unovost run. For premvos, I have nearly reproduced the results with a global mean score about 75 with myself optical flow. 

However, for unovost, I only obtained a 42.5 in terms of global mean, which is not a good result from my opinion. Could you tell me your scores in the validation set? 

One possible explanation about my low score is that I found that in my json files, there is no 'forward_segmentation' item. I modify some codes to skip it. What's the meaning of that item? How can I generate it?

Thanks

**Comment by tfzhou** [comment]
closed without response for too long

**Comment by idilesenzulfikar** [comment]
Hi, @tfzhou, 

Sorry for the late reply. You can find all results of the UnOVOST for the train, validation, test-dev, and challenge sets in our paper by the following link https://arxiv.org/abs/2001.05425v1.

You are also right about the 'forward_segmentation' item. In the 'forward_segmentation' item, we store the optical flow warping for the second step of our implementation. I do not why you have skipped that, but it is important in order to reproduce the results. 

I hope that would be helpful for you :)

**Comment by tfzhou** [comment]
Thanks. It helps. I did not use your optical flow due to the running environment mismatch. I will try to generate the 'forward_segmentation' item using my codes. Thanks.
